# Generated by Django 5.1.1 on 2024-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='license_type',
            field=models.CharField(choices=[('CBT', 'CBT'), ('Full', 'Full')], max_length=4),
        ),
    ]
